### ISSUE TITLE
[Feat] WritingView 쇼케이스에 맞게 수정

### ISSUE THREAD

**Issue by LeeChangHyeong** [TeamGoodGood/RelayNovel_iOS#119]
**Issue : Feature**
- x버튼, 완료버튼 상단 고정
- 음소거 버튼 구현
- ?버튼 대신 텍스트로 구현

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] x버튼, 완료버튼 상단 고정
- [x] 음소거 버튼 구현
- [x] ?버튼 대신 텍스트로 구현
