### ISSUE TITLE
[Fix] MainView 캐릭터, 캐릭터 크기, 위치 수정

### ISSUE THREAD

**Issue by LeeChangHyeong** [TeamGoodGood/RelayNovel_iOS#121]
**Issue : Feature**
- MainView 캐릭터 수정
- MainView 캐릭터 크기, 위치 수정

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] 캐릭터 에셋 추가
- [x] 캐릭터 크기 수정
- [x] 캐릭터 위치 수정
