### ISSUE TITLE
[Feat] MockStory에 달리는중/완주, 최신순/오래된순/추천순, 카테고리별, 내가 시작한/참여한/좋아요한 Story 제공 필터기능 구현 및 해당 View 연결

### ISSUE THREAD

**Issue by JaewoongLee-swift** [TeamGoodGood/RelayNovel_iOS#134]
**Issue : Feature**
MockStory에 달리는중/완주, 최신순/오래된순/추천순, 카테고리별, 내가 시작한/참여한/좋아요한 Story 제공 필터기능 구현 및 해당 View 연결

**Description**
쇼케이스 데모앱 구현을 위한 MockStory에 달리는중/완주, 최신순/오래된순/추천순, 카테고리별, 내가 시작한/참여한/좋아요한 Story 제공 필터기능 구현 및 각 데이터가 필요한 View에 연결이 필요합니다,

**Todo**
- [x] MockStory에서 달리는중/완주 데이터 제공기능 구현
- [x] MockStory에서 최신순/오래된순/추천순 데이터 제공기능 구현
- [x] MockStory에서 카테고리별 데이터 제공기능 구현
- [x] MockStory에서 내가 시작한/참여한/좋아요한 데이터 제공기능 구현
- [x] RelayBrowsingViewController에서 달리는중/완주별로 보여주기 기능 구현
- [x] RelayBrowsingViewController에서 최신순/오래된순/추천순별로 보여주기 기능 구현
- [x] RelayBrowsingViewController에서 카테고리별로 보여주기 기능 구현
- [x] RelayActivityViewController에서 내가 시작한 Story 보여주기 기능 구현
- [x] RelayActivityViewController에서 내가 참여한 Story 보여주기 기능 구현
- [x] RelayActivityViewController에서 내가 좋아요한 Story 보여주기 기능 구현
