### ISSUE TITLE
[Feat] 마이페이지 디자인 UI 변경

### ISSUE THREAD

**Issue by ohhseungyeon** [TeamGoodGood/RelayNovel_iOS#137]
**Issue : Feature**
마이페이지의 UI 디자인을 수정합니다

**Description**
마이페이지의 UI 디자인을 수정합니다

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] 시작한 릴레이, 참여한 릴레이의 수 색상 수정
- [x] 나의 활동 캐릭터 수정
- [x] 나의 활동 폰트, 색상 수정

**Reference(Optional)**
추후 알림 디자인 수정이 필요합니다
