### ISSUE TITLE
[Feat] RelayProfileViewController Hi-fi 디자인으로 레이아웃 수정

### ISSUE THREAD

**Issue by JaewoongLee-swift** [TeamGoodGood/RelayNovel_iOS#14]
**Issue : Feature**
Lo-fi 기준으로 구현된 RelayProfileViewController의 디자인을 Hi-fi 디자인으로 수정해야합니다.

|Lo-fi 구현(현재)|Hi-fi 구현|
|:---:|:---:|
|<img width="300" alt="스크린샷 2022-10-27 오후 2 48 54" src="https://user-images.githubusercontent.com/83946704/198958317-a707062d-d3a5-47ff-b9de-6fa06ab1b8c3.png">|<img width="300" alt="마이페이지 - hi-fi" src="https://user-images.githubusercontent.com/83946704/198995354-0c520014-155d-47ee-809f-dd9fb11e7918.png">|

**Description**
1. RelayProfileUserInfoView의 레이아웃 위치가 변경되고 프로필이미지가 제거되야합니다.
2. RelayProfileUserActivityView의 RelayProfileUserActivityCollectionViewCell의 디자인이 변경되어야 합니다.
3. RelayProfileViewController의 profileSettingButton이 제거되어야 합니다.
4. RelayProfileViewController애 알림버튼이 추가되어야 합니다.

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] RelayProfileUserInfoView 프로필이미지 레이아웃 제거
- [x] RelayProfileUserInfoView 레이아웃 수정
- [x] RelayProfileUserActivityCollectionViewCell 레이아웃 수정
- [x] profileSettingButton 제거
- [x] RelayProfileViewController의 알림버튼 생성
- [x] 버튼, CollectionViewCell 동작확인
- [x] 비로그인 뷰 레이아웃 설정 함수명 오타 수정 ([Comment](https://github.com/TeamGoodGood/RelayNovel-iOS/pull/13#discussion_r1009276941))

**Reference(Optional)**
1. 정확한 Constraints 값은 스타일가이드가 완성된 후 작업되야합니다.
2. 포인트컬러 및 아이콘은 스타일가이드가 완성된 후 작업되야 합니다.
3. TabBarController가 구현된 후 레이아웃 및 Constraints 테스트가 필요합니다
