### ISSUE TITLE
[Feat] RelayAgreementView 구현

### ISSUE THREAD

**Issue by LeeChangHyeong** [TeamGoodGood/RelayNovel_iOS#20]
**Issue : Feature**
RelayAgreementView UI 구현

**Description**
Figma
<img width="481" alt="image" src="https://user-images.githubusercontent.com/71262367/199223929-4ad3d457-95a6-49b3-9c74-956ebf5dacf6.png">

CollectionView를 사용하고 Cell을 재사용하여 구현해 볼 생각입니다.

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [ ] 백 버튼 구현
- [x] titleLabel 구현
- [ ] 재사용 Cell 만들기
- [x] 확인 버튼 만들기
- [x] 확인 활성화 로직 짜기
