### ISSUE TITLE
[Feat] RelayBrowsingViewController 레이아웃 구현

### ISSUE THREAD

**Issue by JaewoongLee-swift** [TeamGoodGood/RelayNovel_iOS#30]
**Issue : Feature**
RelayBrowsingViewController의 레이아웃 및 동작 구현

|RelayBrowsingViewController 구조|
|:---:|
|[![](https://mermaid.ink/img/pako:eNpd099ruzAQAPB_5QhsTyvfp730YTB_rW4VRjfH-GqRoNcaGhOJcaW0_d8XY612Pki4-3B3xuRIclkgmZOtonUJy1UqwDzPyQo5PThK7hsmtl8M964UWknOUa1hNps9wSkOu_jJubULpAWqLrO-1Lrlbs-XrNET5MDUeMlQ7ZNpjhPnDc5ptZbi5N_KPvrX2prBrYyFmZIzMS3ev-_uLtO4SRz-i7_hXUkt9aHG9RW4FnjHsKo5Vig01UyK8zV_af3MOeyl2kGtZI5NA6yBPdMlxKGNm_EDxjUqcEsqtphFmJsFa6qxlW9LBUlEdwiP0PsxHdj0y586cTiKFysWiUsrVBQCZX4k3IND892IFhaFAwqFKabauvsqWFBRmJ3ajjq0-nXQH6XZdtPc32ww1yN7tewtcc0RgxVuaK7lZPS3Lr1Msiz6eofIGA4e_iCXNfiiyDIryQMxPSrKCnNIj10kJbo0e56SuVkWpmrLdUpScTaUtlp-HERO5lq1-EDauqAaPUbN8a7IfEN5c436BTPjDLKm4r-Uo0GbjfrLYe_I-RcTfwRJ?type=png)](https://mermaid.live/edit#pako:eNpd099ruzAQAPB_5QhsTyvfp730YTB_rW4VRjfH-GqRoNcaGhOJcaW0_d8XY612Pki4-3B3xuRIclkgmZOtonUJy1UqwDzPyQo5PThK7hsmtl8M964UWknOUa1hNps9wSkOu_jJubULpAWqLrO-1Lrlbs-XrNET5MDUeMlQ7ZNpjhPnDc5ptZbi5N_KPvrX2prBrYyFmZIzMS3ev-_uLtO4SRz-i7_hXUkt9aHG9RW4FnjHsKo5Vig01UyK8zV_af3MOeyl2kGtZI5NA6yBPdMlxKGNm_EDxjUqcEsqtphFmJsFa6qxlW9LBUlEdwiP0PsxHdj0y586cTiKFysWiUsrVBQCZX4k3IND892IFhaFAwqFKabauvsqWFBRmJ3ajjq0-nXQH6XZdtPc32ww1yN7tewtcc0RgxVuaK7lZPS3Lr1Msiz6eofIGA4e_iCXNfiiyDIryQMxPSrKCnNIj10kJbo0e56SuVkWpmrLdUpScTaUtlp-HERO5lq1-EDauqAaPUbN8a7IfEN5c436BTPjDLKm4r-Uo0GbjfrLYe_I-RcTfwRJ)|

|RelayBrowsingViewController - Figma|RelayBrowsingViewController(with Modal) - Figma|
|:---:|:---:|
|<img width="300" alt="둘러보기 - Figma" src="https://user-images.githubusercontent.com/83946704/199669949-9ea8834d-2078-4cc6-8a5b-62ecbe01598e.png">|<img width="300" alt="둘러보기(모달) - Figma" src="https://user-images.githubusercontent.com/83946704/199905454-32fc534c-0596-40bd-a49f-e87d3089da10.png">|

**Description**
1. RelayBrowsingViewController의 레이아웃을 구현해야합니다.
2. BrowsingTitleButton을 터치하면 RelayBrowsingHeaderView이 동작하도록 구현해야합니다.
3. '카테고리 전체' 버튼을 터치하면 모달이 뜨도록 구현해야합니다.

**Todo**
- [x] RelayBrowsingViewController의 레이아웃 구현
- [x] BrowsingTitleButton을 터치하면 RelayBrowsingHeaderView이 동작하도록 구현
- [x] '카테고리 전체' 버튼을 터치하면 모달이 뜨도록 구현
