### ISSUE TITLE
[Feat] RelayReadingViewController 구현

### ISSUE THREAD

**Issue by JaewoongLee-swift** [TeamGoodGood/RelayNovel_iOS#41]
**Issue : Feature**
1. RelayReadingViewController의 감상용 on/off 레이아웃 구현
2. RelayReadingViewController의 감상용 on/off 버튼동작 구현
3. RelayReadingViewController의 이어쓰기 기능 구현
4. RelayReadingViewController의 완결 레이아웃 구현

|읽기(감상모드) - Figma|읽기(히스토리) - Figma|읽기(히스토리 + 이어쓰기) - Figma|읽기(감상모드 + 완결) - Figma|
|:---:|:---:|:---:|:---:|
|<img width="300" alt="읽기 - 감상모드" src="https://user-images.githubusercontent.com/83946704/200311347-04a4206e-4b92-4ec9-aa88-f82dae5732d6.png">|<img width="300" alt="읽기 - 히스토리" src="https://user-images.githubusercontent.com/83946704/200311392-dd48f415-82e5-47b4-8cae-59259ce30a3f.png">|<img width="300" alt="읽기 - 히스토리 + 이어쓰기" src="https://user-images.githubusercontent.com/83946704/200311443-f8a38d90-cd39-4b1f-a005-c433e241de29.png">|<img width="300" alt="읽기 - 감상 + 완결" src="https://user-images.githubusercontent.com/83946704/200311472-4d63eb5e-f1fd-4462-a8e6-45d263e542b9.png">|

**Description**
1. RelayReadingViewController의 감상용 on/off의 레이아웃을 구현해야합니다.
2. RelayReadingViewController의 감상용 on/off 버튼동작에 따라 레이아웃이 변경되도록 구현해야합니다.
3. RelayReadingViewController의 '바통 터치' 버튼을 누르면 입력이 가능하도록 구현해야합니다.
4. RelayReadingViewController의 완결 레이아웃을 구현해야 합니다.

**Todo**
- [x] RelayReadingViewController의 감상용 on/off의 레이아웃을 구현
- [x] RelayReadingViewController의 감상용 on/off 버튼 로직 구현
- [x] RelayReadingViewController의 이어쓰기 기능 구현
- [x] RelayReadingViewController의 완결 레이아웃 구현

**Reference(Optional)**
