### ISSUE TITLE
[Feat] RelayCategoryViewController를 재사용하기 위한 리팩토링

### ISSUE THREAD

**Issue by JaewoongLee-swift** [TeamGoodGood/RelayNovel_iOS#42]
**Issue : Feature**
현재 RelayBrowsingViewController에서 쓰이는 RelayCategoryViewController를 RelayWritingViewController에서 재사용할 수 있도록 리팩토링이 필요합니다.

|RelayBrowsingViewController(with Modal) - Figma| RelayCategoryViewController(with Modal) - Figma|
|:---:|:---:|
|<img width="300" alt="둘러보기(모달) - Figma" src="https://user-images.githubusercontent.com/83946704/200390083-619bf06a-f1ba-4180-bfd0-eaaf91bc54e6.png">|<img width="300" alt="글쓰기(모달) - Figma" src="https://user-images.githubusercontent.com/83946704/200390111-01083c25-b4c6-4c97-8be7-5a8bb3334abf.png">|

**Description**
1. 카테고리에 원하는 데이터를 넣을 수 있도록 구현해야합니다.
2. 선택한 카테고리를 '적용하기'버튼을 눌렀을 경우에만 모달을 나타낸 창에 데이터를 전달해야합니다.
3. 다시 모달을 띄우면 이전에 선택한 카테고리가 모달에서 선택되도록 구현해야합니다.
4. '적용하기'버튼의 텍스트가 검정색으로 뜨는 오류를 해결해야합니다.

**Todo**
- [ ] 카테고리에 원하는 데이터를 넣을 수 있도록 구현
- [ ] 선택한 카테고리를 '적용하기'버튼을 눌렀을 경우에만 모달을 나타낸 창에 데이터를 전달하도록 구현
- [ ] 이미 선택한 카테고리를 모달에 전달하도록 구현
- [ ] '적용하기'버튼 텍스트색상 오류 수정

**Reference(Optional)**
리팩토링 이후 RelayWritingViewController에 기능적용이 필요합니다.
