### ISSUE TITLE
[Feat] 앱 전체 기능동작 확인 및 데이터생성/호출로직 구현

### ISSUE THREAD

**Issue by JaewoongLee-swift** [TeamGoodGood/RelayNovel_iOS#74]
**Issue : Feature**
앱 전체 기능동작 확인 및 데이터생성/호출로직 구현

**Description**
1. 앱 전체의 기능이 정상적으로 동작하는지 확인해야합니다.
2. 정상적으로 데이터를 생성할 수 있도록 로직을 구현해야합니다.
3. Mock 데이터를 활용해 정상적으로 뷰 간의 데이터가 전달되도록 구현해야합니다.

**Todo**
- [ ] 앱 전체 기능동작 확인
- [ ] 데이터 모델 수정
- [ ] 데이터 생성로직 구현
- [ ] Mock 데이터를 활용한 뷰 간 데이터 전달 구현
