### ISSUE TITLE
[Design] 전체적인 디자인 수정

### ISSUE THREAD

**Issue by LeeChangHyeong** [TeamGoodGood/RelayNovel_iOS#76]
**Issue : Feature**
- 글쓰기뷰의 '종목','터치' 누르면 글씨 검정색이 아닌 흰색으로 변경
- 글씨뷰의 'X'버튼 누르면 애니메이션으로 내려가도록
- 네비게이션 로고벼튼(메인뷰, 둘러보기뷰) 이미지 크기조절
- 알림뷰 휴지통 버튼 제거

**Todo**
- [x] 글쓰기뷰의 '종목','터치' 누르면 글씨 검정색이 아닌 흰색으로 변경
- [x] 글씨뷰의 'X'버튼 누르면 애니메이션으로 내려가도록
- [x] 네비게이션 로고버튼(메인뷰, 둘러보기뷰) 이미지 크기조절
- [x] 알림뷰 휴지통 버튼 제거
