### ISSUE TITLE
[Feat] 마이페이지 UI 레이아웃 구현

### ISSUE THREAD

**Issue by JaewoongLee-swift** [TeamGoodGood/RelayNovel_iOS#8]
**Issue : Feature**
마이페이지 View의 UI 레이아웃을 구현해야합니다

|마이페이지 View (Figma)|마이페이지 View(비회원상태)|
|:---:|:---:|
|<img width="215" alt="스크린샷 2022-10-27 오후 2 48 54" src="https://user-images.githubusercontent.com/83946704/198202038-fa5dbe21-4667-4fee-8e30-fc4433e1bc16.png">|<img width="217" alt="스크린샷 2022-10-27 오후 2 49 31" src="https://user-images.githubusercontent.com/83946704/198202107-44499c00-e1df-47f5-a11c-f5a16c09b67e.png">|

**Description**
1. 로그인 여부에 따라서 마이페이지 UI의 구성을 변경해야합니다.
2. '나의 활동' 리스트에 버튼이 확장될 가능성을 고려해 CollectionView로 구현해야합니다.

**Todo**
- [x] 마이페이지 UI 레이아웃 구현
- [ ] 각 버튼 테스트 동작 구현
- [x] '나의 활동' 리스트 CollectionView 구현
- [x] 비회원상태일 때 UI 배치변경 구현

**Reference(Optional)**
1. Hi-fi가 확정나지 않은 상황이므로 Constraints의 값들은 Figma에 나타난 값을 참고해 임의로 설정해야합니다.
2. 이후 마이페이지는 RelayProfileView로 네이밍을 변경하겠습니다.
