### ISSUE TITLE
[Feat] 플레이리스트 구현

### ISSUE THREAD

**Issue by LeeChangHyeong** [TeamGoodGood/RelayNovel_iOS#84]
**Issue : Feature**
- BGM을 클릭하면 노래 재생
- 다른 BGM을 클릭하면 전 BGM이 끊기고 새로운 BGM시작

**Description**
- 노래를 듣고 선택할 수 있는 플레이리스트를 구현

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] BGM을 클릭하면 노래 재생
- [x] 다른 BGM을 클릭하면 전 BGM이 끊기고 새로운 BGM시작
- [x] submit버튼을 안 누르고 내리면 전의 BGM 재생 필요
